### ISSUE TITLE
Unable to read Chinese aloud, it is normal to read English aloud.

### ISSUE THREAD

**Issue by jiayouzl** [Mahamedm/Simplified-tts-chrome_extension#1]
Unable to read Chinese aloud, it is normal to read English aloud.

**Comment by Mahamedm** [comment]
you can change line 17-19 on "tts.js" to this:<br> `chrome.tts.speak(selectedText, {
        'lang':'zh-CN',
        'rate': 0.8 
      });`<br>That should make it read Mandarin-Chinese and the "rate" controls the speed of reading. <br>Hope that helps :)
